authors:
  nicof2000:
    name: Nico Felbinger
    description: computer science student
    avatar: https://github.com/felbinger.png
  tnt2k:
    name: tnt2k
    description: ""
    avatar: https://github.com/TheCataliasTNT2k.png
